### ISSUE TITLE
It appears as though the logic is wrong, downloading is swapped with upload.

### ISSUE THREAD

**Issue by Leopere** [openspeedtest/Speed-Test#16]
It appears that my download is swapped with my upload using the latest docker image.

<img width="2528" alt="image" src="https://user-images.githubusercontent.com/1068374/179781258-5a2e8454-e8e6-46b4-a647-81b6488efb43.png">

**Comment by openspeedtest** [comment]
Just tested the latest docker image,  using Bandwidth limit option Chrome, 5Mbps for download and 8Mbps for upload
![Screen Shot 2022-07-19 at 8 35 29 PM](https://user-images.githubusercontent.com/51720450/179783942-71ae608a-e07b-4651-b203-8128bd6a8dbf.png)
It's working as expected.
Clear browser cache and try again 
or try Incognito window.

**Comment by Leopere** [comment]
Perhaps it's confused due to being behind Traefik.  Let me open my instance up from behind my WAF if you wish to test.

```yaml
version: "3.9"
services:
  speed:
    image: openspeedtest/latest
    deploy:
      replicas: 1
      placement:
        constraints:
#          - node.labels.role == db
          - node.hostname == ertest.nixc.us
#          - node.labels.dns == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.speed.tls=true"
        - "traefik.http.services.speed.loadbalancer.server.port=3000"
        - "traefik.http.routers.speed.rule=Host(`speed.nixc.us`)"
        - "traefik.http.routers.speed.entrypoints=websecure"
        - "traefik.http.routers.speed.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.speed.service=speed"
        - "traefik.docker.network=traefik"
        # - 'traefik.http.routers.speed.middlewares=authelia@docker'
    networks:
      # - default
      - traefik

networks:
  traefik: 
    external: true
  # default:
  #   external: false
  ```
