### ISSUE TITLE
I think upload is broken?

### ISSUE THREAD

**Issue by shanehughes1990** [openspeedtest/Speed-Test#31]
My net specs I pay for
1gbps down/750mbps up
I see usually in the neighbourhood of around 650-750 down and about 500-600 up typically throughout the day,
I deployed this to a gke cluster and ran a test from the gke cluster to home, this is the results.
![image](https://user-images.githubusercontent.com/31993465/188179058-056421d4-79c5-4dc1-a3d4-c77852b52a04.png)

The download speed is typical of what I would see from lets say speettest.net, the upload though is definitely broken.
The docker image I used was openspeedtest/latest:latest (pushed 15 days ago from typing this)
`DIGEST:sha256:2b058dda797e8bac0861a92cf5e6a34afbdf748b07f3b16fc65347916b62e504`

Results from speed test immediately after running the openspeedtest one with negligible network traffic differences from my device
![image](https://user-images.githubusercontent.com/31993465/188179841-96bbeea6-727f-4c8e-8c50-f3221daeb945.png)

it's almost like the decimal place is off by 2 digits like I would expect to see around 579.64 would be normal for me

**Comment by openspeedtest** [comment]
Behind reverse proxy? https://github.com/openspeedtest/Speed-Test#docker-install-instructions

**Comment by shanehughes1990** [comment]
Wow I have to apologize, I completely glazed over that 🤣, I set it to 10G I suppose it makes sense... the new results 
![image](https://user-images.githubusercontent.com/31993465/188192766-38dea9c6-5f09-453e-9c89-0d7c5526a84f.png)
Which is actually accurate due to the fact that gke depending on the machine type limits bandwidth currently capped at 300 so this is accurate now, Thank you for the assistance apologize again for glazing over that part......

**Comment by shanehughes1990** [comment]
For the k8s people
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ISSUER-NAME
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10240m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: INGRESS-RESOURCE-NAME
  namespace: NAMESPACE-NAME
spec:
  rules:
  - host: DNS-ADDRESS
    http:
      paths:
      - backend:
          service:
            name: SERVICE-NAME
            port:
              name: SERVICE-PORT-NAME
        path: /
  tls:
  - hosts:
    - DNS-ADDRESS
    secretName: TLS-SECRET-NAME
```
