### ISSUE TITLE
Unrealisticly high upload measurements

### ISSUE THREAD

**Issue by apiening** [openspeedtest/Speed-Test#4]
While my download measurements with OpenSpeedtest compare close to other measurements I did and the values are pretty much expected, my upload measurements are way higher than it is technically possible.
My home internet connection has an upload rate of 30 Mbps on paper, and my measurements with **LibreSpeed** are around **33 Mbps**. However, OpenSpeedtest reports **2351.2 Mbps**.

Any idea what may cause this?
I'm using a reverse proxy for SSL (Traefik) in front of the official Docker image, if that matters.
The only guess I have is that there's some kind of compression going on. But I don't have this issue with **LibreSpeed** and it is set up the same way and is even running on the same server.

**Comment by openspeedtest** [comment]
What was the download speed reported? That was expected result?
Definately upload data is getting compressed.
Try docker image without any modification. 
We are not using any server side language to avoid data compression. We are doing it via Nginx config. So Nginx behaviour is critical. Avoid using any other server infront of Nginx. Otherwise make similar configuration on your server like turn off Gzip etc. Look at Nginx config for more information.

**Comment by openspeedtest** [comment]
You can use your own certificate in docker itself. 

https://hub.docker.com/u/openspeedtest

How to use your own SSL Certificate?

You can mount a folder with your own SSL certificate to this docker container by adding the following line to the above command.

-v /PATH-TO-YOUR-OWN-SSL-CERTIFICATE**:/etc/ssl/**

I am adding a folder with nginx.crt and nginx.key from my desktop by using the following command.

docker run -v /Users/vishnu/Desktop/docker/:/etc/ssl/ --restart=unless-stopped --name openspeedtest -d -p 3000:3000 -p 3001:3001 openspeedtest/latest

**Comment by apiening** [comment]
Yes, the reported download speed had the expected result. The value is very close if not exactly the download speed that LibreSpeed reported as well.

Unfortunately I don't have the option to run OpenSpeedtest on it's own IP. I have over 30 services running on the system, all behind the SSL / reverse proxy.

Can you tell how the data that is posted during the upload speed test is generated? If it contains just zeroes or a very simple repeated pattern that would explain why it could be compressed at a very high rate.

I have opened a support request at the community forum for Traefik, asking if there is an option available to tell the client / browser to not compress the post data (see https://community.traefik.io/t/modify-header-to-disallow-compression-per-docker-service/12582).

**Comment by openspeedtest** [comment]
Yes, it is easily compressible data, i don't think it is a good idea to generate hard to compress data at client side (Think about devices with poor performance or a device from 2008 or 10) so we disable compression option via Nginx. 

In Nginx all you need to do is add "gzip off;" to your config. 

Take a look at our Nginx config. 
https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf 

You don't have to run it on it's own ip address. You can add your own SSL Certificate to the docker image. That is explained in the my second comment. 

I don't know much about Traefik.

Ask then about turn off or add header to specific location 

like yourdomain.com/upload

"upload" is a static file. So you need to enable post to static file.

In Nginx we do "error_page  405     =200 $uri;" to enable POST to static file.

Take a look at browser console and network tab while upload test is running and see what is the error message.

if there is no error message you need to disable compression algorithms like Gzip from server side.

**Comment by Cebrain** [comment]
Only for documentation, i have the same problem with traefik and openspeedtest

**Comment by apiening** [comment]
Unfortunately, I have no answer on my post in the Traefik forum.

I tried to catch the difference between the **Nginx** config and Traefik, but I can't figure out the relevant setting.

I still think this issue might be solvable with a different configuration for the **Traefik** proxy, but I wonder why I don't observe a similar issue with the **LibreSpeed** speedtest (https://github.com/librespeed/speedtest).
I'm running **LibreSpeed** with exactly the same configuration and the upload speed is not affected / reported correctly.

> You don't have to run it on it's own ip address. You can add your own SSL Certificate to the docker image. That is explained in my second comment.

I have one single IP address on the web server and the ports 80 and 443 are occupied. Since I want to have all services running on **HTTPs standard port 443**, I can't see any way other than using the Domain / SNI based reverse proxy that serves all the other HTTPs based services as well.

**Comment by Cebrain** [comment]
I also checked the traefik documentation, till now i couldn't find anything to resolve this problem.
For me also i want to use traefik because the used ports

**Comment by openspeedtest** [comment]
Turn off Compression https://doc.traefik.io/traefik/v2.0/middlewares/compress/

@apiening They are using php to handle this and we use Nginx then turn off Gzip. 

You can mount SSL certificate via docker. 

You need to write a custom configuration in  traefik to handle compression and SSL. 

I am familiar with traefik. Still I like to give it a try. And I will post an update if I got it working. 

You guys are using Let's Encrypt or commercial SSL ? 

And post the configuration if possible. 

Thanks 👍

**Comment by Cebrain** [comment]
@openspeedtest thanks for your response and pointing in the correct direction.

After adding the label to my container, i only get 10mbit download speed (before 1000mbit) and upload is still the same problem with 2500mbit

At the moment i use a local https cert, that isnt from Lets Encrypt.

**Comment by openspeedtest** [comment]
We need http1.1 

Disable compression label (or any other changes) and try 

## Dynamic configuration
[http.serversTransports.mytransport]
  disableHTTP2 = true

https://doc.traefik.io/traefik/master/routing/services/

**Comment by openspeedtest** [comment]
I setup Traefik on my local machine. 
While uploading from Chrome console I can see Connection reset error message. 
![20211204_132154](https://user-images.githubusercontent.com/51720450/144702120-3cabde30-393a-4ae3-b43f-db44e5bd34a8.jpg)

Can you post docker your docker compose file with labels you used? 

Also take a look ar browser console. 

If possible post logs from Traefik after a test.

**Comment by openspeedtest** [comment]
running without error after adding 
traefik.http.routers.openspeedtest.tls=true
i was running without ssl.

This is from a local machine. 


```
version: '2'

services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    labels:
      - traefik.enable=true
      - traefik.http.routers.openspeedtest.rule=Host(`speed.localhost`)
      - traefik.http.routers.openspeedtest.entrypoints=web
      - traefik.docker.network=web
      - traefik.http.services.openspeedtest.loadbalancer.server.port=3000
      - traefik.http.routers.openspeedtest.tls=true
      
    restart: unless-stopped
    networks:
      - web
    ports:
      - 3000:3000

networks:
  web:
    external:
      name: web

```


https://user-images.githubusercontent.com/51720450/144702677-3d313254-8ed7-4a57-8c53-d359563121a2.mp4

**Comment by Cebrain** [comment]
I have the same setting but still the same problem, but i found something out.

When i use the Internet Explorer (on WIndows 10) it works fine.
![image](https://user-images.githubusercontent.com/78339531/144708979-76626c28-c368-4fcd-8990-e671d6bb472e.png)

On Firefox:
![image](https://user-images.githubusercontent.com/78339531/144708878-633c8169-2725-449c-a3b4-cf0cb315e127.png)

On Edge Browser (Chromium Based) is the absulut Winner
![image](https://user-images.githubusercontent.com/78339531/144708934-b99c132f-6c83-40c8-a480-b4baecf35159.png)

**Comment by openspeedtest** [comment]
Take a look at your browser console and network tab while upload test is going on. 
And post a screenshot if you see any error.
Also post logs / full config including compose file for openspeedtest and traefik
It will be useful for everyone.

**Comment by openspeedtest** [comment]
try 
labels:
  - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10000000000"

The error was when we trying to test upload speed which is sending sever url with 30Mb of data but traefik for some reason preventing or doing something wrong. After adding maxRequestBodyBytes to  10000000000. Issue resolved for me. 

I tested this on my local machine by running Nginx 

```
http:
  routers:
    router1:
      service: myService
      middlewares:
        - "maxRequest-fix"
      rule: "Host(`192.168.1.170`)"
      tls: true
    
   

  middlewares:
   maxRequest-fix:
      limit:
      buffering:
        maxRequestBodyBytes: 10000000000

  services:
    myService:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:4000"
```

I will test docker and post updates.

**Comment by Cebrain** [comment]
@openspeedtest 
Thanks, this limit setting fixed the problem. Tested it on my instance 👍

**Comment by openspeedtest** [comment]
try
````
version: "3.9"
services:
traefik:
image: traefik:v2.8.0
container_name: traefik
command:
- --log.level=INFO
- --api.insecure=true
- --providers.docker=true
- --providers.docker.exposedbydefault=false
- --entrypoints.web.address=:80
ports:
- 3000:80
- 8080:8080
volumes:
- /var/run/docker.sock:/var/run/docker.sock:ro
openspeedtest:
image: openspeedtest/latest
container_name: speedtest-service
labels:
traefik.enable: 'true'
traefik.http.routers.openspeedtest.rule: Host(`192.168.1.128`)
traefik.http.routers.openspeedtest.entrypoints: web
traefik.http.middlewares.limit.buffering.maxRequestBodyBytes: 10000000000
traefik.http.routers.openspeedtest.middlewares: limit

````

**Comment by openspeedtest** [comment]
> [k8s people check this
> ](https://github.com/openspeedtest/Speed-Test/issues/31#issuecomment-1235671004)

**Comment by openspeedtest** [comment]
[Nginx reverse proxy ](https://github.com/openspeedtest/Speed-Test/issues/23#issuecomment-1226781139)

**Comment by openspeedtest** [comment]
[IIS SERVER ](https://github.com/openspeedtest/Nginx-Configuration)
[Nginx Server](https://github.com/openspeedtest/Nginx-Configuration)

**Comment by openspeedtest** [comment]
Caddy https://github.com/openspeedtest/Speed-Test/issues/67

**Comment by openspeedtest** [comment]
Reverse Proxy is Expensive. Your server will consume more CPU & RAM. **Do not run it behind a reverse proxy unless it's absolutely necessary.** 
- If your server is very powerful, you may not notice a performance drop while running this behind a reverse proxy. 
- If you use this on a raspberry pi, you will see a huge performance drop when running behind a reverse proxy.
- Bad configuration, such as not using hardware for encryption and decryption, may also lead to poor performance. 
- Run tests with and without reverse proxy.
- If the performance is adequate, deploy it.

**Comment by milindpatel63** [comment]
I am still having this issue, but only in chromium based browsers.
I am running openspeedtest in Docker on Ubuntu with traefik in front of it pointing to http of openspeedtest with no middleware.

On my local network on another windows PC via gigabit ethernet,
on Chrome
Download: 865 Mbps
Upload: 18254 Mbps

on Firefox
Download: 798 Mbps
Upload: 670 Mbps

After adding `maxRequestBodyBytes: 10000000000` in middleware,
on Chrome
Download: 7 Mbps
Upload: 603 Mbps

on Firefox
Download: 365 Mbps
Upload: 458 Mbps

I have tried 3 chromium based browsers (Chrome, Edge, and Thorium), all have same result.
On firefox it's all fine.
No error in console on chrome.
Also, no error in openspeedtest docker logs.

Since, it's specific to chromium browsers, I think its not related to traefik.

**Comment by openspeedtest** [comment]
Add 
traefik.http.routers.openspeedtest.middlewares: limit
@milindpatel63

**Comment by milindpatel63** [comment]
> Add traefik.http.routers.openspeedtest.middlewares: limit @milindpatel63

yes, ofcourse, i have added that.
I don't use docker labels for traefik config. Instead I use traefik's file based config.
Here's my relevant config.yml

```
http:
  routers:
    openspeedtest:
      entryPoints:
        - "https"
      rule: "Host(`openspeedtest.example.com`)"
      middlewares:
        - openspeedtest-limit
      tls: {}
      service: openspeedtest
  services:
    openspeedtest:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
        passHostHeader: true
  middlewares:
    openspeedtest-limit:
      buffering:
        maxRequestBodyBytes: 10000000000
```
