### ISSUE TITLE
Can't use different port other than 3000 in docker

### ISSUE THREAD

**Issue by MekayelAnik** [openspeedtest/Speed-Test#84]
If I use a different port other than 3000 it does not load on that port, rather it loads on 3000 port.
Notes:
- I am using docker compose to do so
- I am using macvlan to set a local IP to my container
- I am trying to use port 80 instead of 3000

So, when I do so, the WebUI does not load on <container-ip>, rather loads on  <container-ip>:3000

**Comment by openspeedtest** [comment]
post you docker compose

**Comment by MekayelAnik** [comment]
#### Container Specific Configs ####
services:
  speedtest:
      image: openspeedtest/latest:latest
      container_name: openspeedtest
      environment:
        - TZ=Asia/Dhaka
  #    volumes:
  #      -v /${PATH-TO-YOUR-OWN-SSL-CERTIFICATE}:/etc/ssl/
      ports:
        - 80:3000
        - 443:3001
      dns:
        - 1.1.1.1
        - 1.0.0.1
      restart: always
#### Network Specific Configs ####
      hostname: openspeedtest
      domainname: local
      mac_address: aa-ee-ae-dd-bb-cc
      networks:
        my-macvlan:
          ipv4_address: 192.168.1.123
#### Network Defination ####
networks:
  my-macvlan:
    name: my-macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0"
          ip_range: "192.168.1.0/24"
          gateway: "192.168.1.1"

**Comment by openspeedtest** [comment]
List the Docker containers you are running.
Check for other `openspeedtest` containers already running on port 3000.
Run the `docker whoami` image with the same configuration and see if you can access the container.
Once it is working fine with the `whoami` image, switch the image to `openspeedtest`
If you run 
````
    ports:
      - 80:3000
      - 443:3001
````
You cannot access it from port 3000. The cached page may load, but when you click Start, it will show a Network Error.

**Comment by MekayelAnik** [comment]
there is no other `openspeedtest` container running.
And I have used Incognito mode so that no previous cache is served.

**Comment by openspeedtest** [comment]
Did you run whoami image instead of openspeedtest? I am trying to isolate the issue here.

**Comment by openspeedtest** [comment]
Or run `hello-world` image, to make sure everything else in your setup is working fine.

**Comment by MekayelAnik** [comment]
I have used "traefik/whoami" image.
It returned:
```
Hostname: openspeedtest
IP: 127.0.0.1
IP: 192.168.1.123
RemoteAddr: 192.168.1.17:51767
GET / HTTP/1.1
Host: 192.168.1.123
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en
Cache-Control: max-age=0
Connection: keep-alive
Sec-Gpc: 1
Upgrade-Insecure-Requests: 1
```

Docker Compose in this case:

`---
version: "3.9"

#### Container Specific Configs ####
services:
  speedtest:
      image: traefik/whoami:latest
#      image: openspeedtest/latest:latest
      container_name: openspeedtest
      environment:
        - TZ=Asia/Dhaka
  #    volumes:
  #      -v /${PATH-TO-YOUR-OWN-SSL-CERTIFICATE}:/etc/ssl/
      ports:
        - 80:3000
        - 443:3001
      dns:
        - 1.1.1.1
        - 1.0.0.1
      restart: always
#### Network Specific Configs ####
      hostname: openspeedtest
      domainname: local
      mac_address: aa-ee-ae-dd-bb-cc
      networks:
        macvlan-RasPi4B:
        my-macvlan:
          ipv4_address: 192.168.1.123
#### Network Defination ####
networks:
  my-macvlan:
    name: my-macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0"
          ip_range: "192.168.1.0/24"
          gateway: "192.168.1.1"
`

**Comment by openspeedtest** [comment]
Yea, I tested port 80 and 443 worked without any issue. 

`docker logs openspeedtest`
what is the output?

I don't know why it's not working on your setup. Maybe macvlan is the reason, but I don't have much knowledge in this area.
 
I Asked Bard! :) 
````
version: "3.9"

#### Container Specific Configs ####
services:
  speedtest:
    image: traefik/whoami:latest
#    image: openspeedtest/latest:latest
    container_name: openspeedtest
    environment:
      - TZ=Asia/Dhaka
    #    volumes:
    #      -v /${PATH-TO-YOUR-OWN-SSL-CERTIFICATE}:/etc/ssl/
    ports:
      - 80:3000
      - 443:3001
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always

#### Network Specific Configs ####
    hostname: openspeedtest
    domainname: local
    mac_address: aa-ee-ae-dd-bb-cc
    networks:
      macvlan-RasPi4B:
      my-macvlan:
        ipv4_address: 192.168.1.123

#### Network Defination ####
networks:
  my-macvlan:
    name: my-macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0"
          ip_range: "192.168.1.0/24"
          gateway: "192.168.1.1"

````
The line networks: macvlan-RasPi4B: was added to the services section to specify that the speedtest container should be connected to the macvlan-RasPi4B network.
The line ipv4_address: 192.168.1.123 was added to the my-macvlan network definition to specify the IP address that the speedtest container should be assigned.
The line driver_opts: parent: eth0 was added to the my-macvlan network definition to specify that the my-macvlan network should be bridged to the eth0 interface on the host machine.
