### ISSUE TITLE
Openspeedtest with TLS reverse proxy.

### ISSUE THREAD

**Issue by tuapuikia** [openspeedtest/Speed-Test#89]
Hi, I need some advice. I set up an Nginx reverse proxy with HTTPS and HTTP frontends, and I proxy-pass to an openspeedtest container. I noticed that the bandwidth to the Nginx HTTPS site is 3 times slower than the HTTP site. I enabled kTLS, but it didn't help at all.

**Comment by openspeedtest** [comment]
Can you post your Nginx config?
Did you checked `ENABLE_LETSENCRYPT` option in docker image?
````
version: '3.3'
services:
    speedtest:
       environment:
           - ENABLE_LETSENCRYPT=True
           - DOMAIN_NAME=speedtest.yourdomain.com
           - USER_EMAIL=you@yourdomain.com
       restart: unless-stopped
       container_name: openspeedtest
       ports:
            - '80:3000'
            - '443:3001'
       image: openspeedtest/latest
````
